server.port=8080
github.api.base-url=https://api.github.com

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.urls[0].name=GitHub API
springdoc.swagger-ui.urls[0].url=/openapi.yaml
springdoc.swagger-ui.urls[1].name=Internal API
springdoc.swagger-ui.urls[1].url=/api-docs
